apiVersion: 1

datasources:
  - name: InfluxDB
    uid: influxdbdatasource
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: smartbin
      defaultBucket: smartbin_data
      tlsSkipVerify: true
    secureJsonData:
      token: smartbin-super-secret-token
    isDefault: true
